### ISSUE TITLE
Gas amount per gnosis-safe transaction

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-liquidity-provision#154]
Currently, we still need to adjust the gas amount in metamask, as the gas estimation for the bundled transactions is not working.

One idea to fix it was to use always a very high gas limit for the transactions:

```
const endpoint = `https://safe-transaction.${network}.gnosis.io/api/v1/safes/${masterSafe.address}/transactions/`
    const postData = {
      to: transaction.to,
      value: transaction.value,
      data: transaction.data,
      operation: transaction.operation,
      safeTxGas: 0, // TODO: magic later <---- modify the number here to 5 million
      baseGas: 0,
      gasPrice: 0, // important that this is zero
      gasToken: ADDRESS_0,
      refundReceiver: ADDRESS_0,
      nonce: nonce.toNumber(),
      contractTransactionHash: transactionHash,
      sender: web3.utils.toChecksumAddress(account),
      signature: sigs,
    }
    const ans = await axios.post(endpoint, postData)
```
(it is the function here: https://github.com/gnosis/dex-liquidity-provision/blob/master/scripts/utils/sign_and_send.js#L18)

However, if we set another value bigger than 0, we always get this error:
```
Error: Request failed with status code 422
    at createError (/Users/alexherrmann/gnosis/dex-liquidity-provision/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/alexherrmann/gnosis/dex-liquidity-provision/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/alexherrmann/gnosis/dex-liquidity-provision/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
```

Right now we don't have a proper way to debug it. Our current requests look like this:
```
data:
   '0x8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000357a00bc935bdde7c30ee228b431a602068c1466938698000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000075f8ebf1d7e3affffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff00000000000000000000000000000000070d2ba17b9ee57fffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b99000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000037a2ecff63de3d35bd15bcf1f0d2999437edf9b4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000070d2ba17b9ee57fffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff0000000000000000000000000000000006be6116ead0da7fffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b9900000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000005f239a6671bc6d2baef6d7cd892296e678810882000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000006be6116ead0da7fffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff00000000000000000000000000000000067306f123d2ae7fffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b99000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000067367bcbb0289b5c588bfabafe1328f35405da9a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000067306f123d2ae7fffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff00000000000000000000000000000000062af6c2d7cae8bfffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b99000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000007c8eabadd0d1d791b82cafa241b0ccbebff65cc000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000062af6c2d7cae8bfffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff0000000000000000000000000000000005e60bcc17982f7fffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b990000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000dc4770bb2446efdfbbfe78beb661395eec5976f2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000005e60bcc17982fbfffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff0000000000000000000000000000000005a422e79618b83fffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b990000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000772420c7c911adda17223d49ed383d6bafe4aa33000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000005a422e79618b7ffffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff0000000000000000000000000000000005651a78bbda48bfffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b990000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000c60f18e4158c50cc188d6e84cfe8a14ad3911930000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000005651a78bbda48bfffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000528d25a830ef27fffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b99000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000089845a5c9f1ea30da4ed269ef96fc003c00e8052000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000528d25a830ef27fffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff0000000000000000000000000000000004ef2bcf1308ba7fffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b990000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000cf5188d539794387c24a37ee881ad7c0f83386a7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005046a761202000000000000000000000000c576ea7bd102f7e476368a5e98fa455d1ea34de2000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000480000000000000000000000000000000000000000000000000000000000000030465cc3e7800000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002a00000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000070000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000050bf4f000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000fffffffe00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000004ef2bcf1308babfffffffffffffffff00000000000000000000000000000000ffffffffffffffffffffffffffffffff000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000ffffffffffffffffffffffffffffffff0000000000000000000000000000000004b8097012e0267fffffffffffffffff000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041000000000000000000000000ec9279204c734e335f8b7f7f660de19968f15b9900000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000',
  operation: 1,
  safeTxGas: 500000,
  baseGas: 0,
  gasPrice: 0,
  gasToken: '0x0000000000000000000000000000000000000000',
  refundReceiver: '0x0000000000000000000000000000000000000000',
  nonce: 40,
  contractTransactionHash:
   '0x3e11f97c90ca796fb7d4e84924b7c5ccae9325633f55b9fa6c892238b665cdb1',
  sender: '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1',
  signature:
   '0x4b0d61a5a589c3229080f7bc851dd4caca57ba4b0e6847d7af152a1bf35ca9084bbfaf8eb7ae5e3dee189b475b4ae567c108a56d3fef0be644df5c7845ebff4f1b' }
```

**Comment by fleupold** [comment]
The reason that metamask is mis-estimating safe transactions is that it does a binary search to find the lowest possible gas amount for which the entire meta-transaction succeeds.
Even in the case of a revert/out-of-gas in the inner tx, the outer meta-transaction will still succeed and refund the tx submitter with a gas refund.

This is why Metamask gas estimation is broken in the first place.

Related issues: 
https://github.com/gnosis/safe-react/issues/322
https://github.com/gnosis/contract-proxy-kit/pull/49
https://github.com/gnosis/safe-contracts/pull/188

**Comment by fleupold** [comment]
The correct long term fix according to the safe docs (https://docs.gnosis.io/safe/docs/contracts_tx_execution/#safe-transaction-gas-limit-estimation) is to invoke `requiredTxGas ` and extract the correct number from the revert message.
