### ISSUE TITLE
undefined in wrap_eth script

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-liquidity-provision#238]
When trying to run `wrap_eth` script I got the following error:

```sh
➜  dex-liquidity-provision git:(218/use_verifyBracketsWellFormed) ✗ npx truffle exec scripts/wrap_eth.js --masterSafe 0x8990c564ec303C7b26d3d5556ef0910E58Be08Ce --amount 10 --network rinkeby
> Warning: possible unsupported (undocumented in help) command line option: --masterSafe,--amount
Using network 'rinkeby'.

Wrapped Ether at address 0xc778417E063141139Fce010982780140Aa0cD5Ab
Converting 10 ETH into WETH
Are you sure you want to send this transaction to the EVM? [yN] y
undefined
Error: invalid number value (arg="value", coderType="uint256", value="8ac7230489e80000")
    at Object.throwError (/Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/node_modules/ethers/utils/errors.js:68:1)
    at CoderNumber.encode (/Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:353:1)
    at /Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:605:21
    at Array.forEach (<anonymous>)
    at pack (/Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:604:1)
    at CoderTuple.encode (/Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:764:1)
    at AbiCoder.encode (/Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/node_modules/ethers/utils/abi-coder.js:897:1)
    at ABICoder.encodeParameters (/Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/src/index.js:96:1)
    at /Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-contract/src/index.js:426:1
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/Users/admin/Projects/gnosis/dex-liquidity-provision/node_modules/truffle/build/webpack:/node_modules/web3-eth-contract/src/index.js:425:10)
    at estimateGas (/Users/admin/Projects/gnosis/dex-liquidity-provision/scripts/utils/sign_and_send.js:18:8)
    at signAndSend (/Users/admin/Projects/gnosis/dex-liquidity-provision/scripts/utils/sign_and_send.js:42:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.25 (core: 5.1.25)
Node v10.17.0
```

After some investigation, it appears to be an issue with the recently introduced gas estimation:

https://github.com/gnosis/dex-liquidity-provision/blob/1765ab3b9d5eb1060a8a4c9074dcf1ff8186633a/scripts/utils/sign_and_send.js#L15-L31

**Comment by bh2smith** [comment]
Turns out that the issue was resolved by casting the BN in `transaction.value` `toString`
