### ISSUE TITLE
Script fails unexpectedly after deploying some of the safes

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-liquidity-provision#38]
When deploying many safes, sometimes the script fails unexpectedly after having deployed some safes. This is likely because the web3 provider doesn’t immediately see the newly created safe when requested and returns an error. Maybe we should add a delay after each wallet is created before accessing it on Infura?
 
This is the error:
 
```
Error: Cannot create instance of GnosisSafe; no code at address 0x3a58a6E39B62Fe2FF81e06B0777BB3a476e90f44
    at Object.checkCode (/path/dex-liquidity-provision/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:287:1)
    at Function.at (/path/dex-liquidity-provision/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:74:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.12 (core: 5.1.12)
Node v10.18.1
```

**Comment by fedgiac** [comment]
The same problem happened again. It only happens when deploying to mainnet, never on Rinkeby or testing.
